version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - './config/nginx:/etc/nginx/conf.d'
      - './staticfiles:/static'
    depends_on:
      - todo-app
  todo-app:
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - '.:/todolist'
    ports:
      - '8000:8000'
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: backend
      MYSQL_USER: ahu8867
      MYSQL_PASSWORD: ahu8867pw
    volumes:
      - './.mariadb:/var/lib/mysql'
